#!/bin/sh

echo "Symlinking.."
if [[ "$(uname)" = "Darwin" ]] ; then
    ln -s .vim/.vimrc $HOME
else
    ln -s .vim/.vimrc -t$HOME
fi

echo "Updating submodules"
git submodule update --init --recursive

echo "Installing plugins.."
vim -E -u NONE -S ~/.vim/vundle.vim +PluginInstall +qall > /dev/null
echo "Plugins installed"

echo "External stuff.."
if [[ -z "$GOPATH" ]] ; then
    echo "-- Remember--"
    echo "apt-get install exuberant-ctags"
    echo "go get -u github.com/jstemmer/gotags"
    echo "go get -u github.com/golang/lint/golint"
    echo "go get -u code.google.com/p/go.tools/cmd/vet"
    echo "go get -u code.google.com/p/go.tools/cmd/gotype"
    echo "go get code.google.com/p/go.tools/cmd/oracle"
    echo "-------------"
else
    echo "consider installing vim from brew"
    go get -u github.com/jstemmer/gotags
    go get -u github.com/golang/lint/golint
    go get -u golang.org/x/tools/cmd/vet
    go get -u golang.org/x/tools/cmd/gotype
    go get -u golang.org/x/tools/cmd/oracle
    go get -u github.com/rogpeppe/godef
    go get -u github.com/nsf/gocode

    if [[ "$(uname)" = "Darwin" ]] ; then
        brew install ctags-exuberant
        brew install pandoc
    else
        apt-get -y install exuberant-ctags
        apt-get -y install pandoc
    fi
fi

echo "Compiling YCM (needs cmake, downloads clang) (requires go, nodejs and npm)"
cd ~/.vim/bundle/YouCompleteMe
./install.py --clang-completer --gocode-completer --tern-completer

